[package]
name = "koof-gen"
version = "0.1.0"
edition = "2024"
description = "Generates Kubernetes operator code from OpenAPI + overlays"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
enumset = "1.1.14"
heck = "0.5.0"
prettyplease = "0.3.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
roas-overlay = "0.3.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9"
syn = "3.0.6"
thiserror = "2.0.20"
