[workspace]
resolver = "3"
members = ["crates/providers/cloudflare", "crates/koof"]

[workspace.lints.rust]
warnings = { level = "deny", priority = -1 }
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

unwrap_used = "deny"
expect_used = "deny"
todo = "deny"
dbg_macro = "deny"
