[package]
name = "cloudflare-provider"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
actix-web = "4.15.0"
anyhow = "1.0.104"
futures = "0.3"
k8s-openapi = { version = "0.28.0", features = ["latest"] }
kube = { version = "4.2.0", features = ["runtime", "derive", "client", "rustls-tls"] }
chrono = { version = "0.4", features = ["serde"] }
progenitor-client = "0.15.0"
regress = "0.12"
reqwest = { version = "0.13.5", default-features = false, features = ["json", "rustls", "stream"] }
schemars = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
thiserror = "2"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
